[package]
name = "libdns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
idna = "0.4.0"
itertools = "0.11.0"
nom = "7.1.3"
rand = "0.8.5"
thiserror = "1.0.43"
